name: backstage_connect
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.6
  file_picker: ^8.0.3
  http: ^1.2.1
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  image_cropper: ^7.1.0
  path_provider: ^2.1.4
  fl_chart: ^0.69.0
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/ # 👈 this includes all files inside assets/icons/
    - assets/bg.png
    - assets/logo_B.png

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon.png

  flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png
  android_12:
    color: "#FFFFFF"
    image: assets/splash.png